apiVersion: v1
kind: Pod
metadata:
  name: kickstart-app
  labels:
    name: kickstart-app
spec:
  containers:
  - name: kickstart-app
    image: ramitsurana/kickstart-app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000
