apiVersion: v1
kind: ReplicationController
metadata:
  name: sample
spec:
  replicas: 1
  selector:
    app: sample
  template:
    metadata:
      name: sample
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        image: sample
        ports:
        - containerPort: 8000