apiVersion: v1
kind: Namespace
metadata:
  name: kickstart-app
  labels:
    name: kickstart-app

---
apiVersion: v1
kind: Pod
metadata:
  name: kickstart-app
  namespace: kickstart-app
  labels:
    name: kickstart-app
spec:
  containers:
  - name: kickstart-app
    image: ramitsurana/kickstart-app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: kickstart-app
  namespace: kickstart-app
spec:
  selector:
    app: kickstart-app
  ports:
  - port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kickstart-app
  namespace: kickstart-app
spec:
  replicas: 1
  selector:
    app: kickstart-app
  template:
    metadata:
      name: kickstart-app
      labels:
        app: kickstart-app
    spec:
      containers:
        - name: kickstart-app
          image: ramitsurana/kickstart-app
          ports:
            - containerPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kickstart-app
spec:
  selector:
    matchLabels:
      app: kickstart-app
  template:
    metadata:
      labels:
        app: kickstart-app
    spec:
      containers:
      - name: kickstart-app
        image: ramitsurana/kickstart-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
