apiVersion: v1
kind: Namespace
metadata:
  name: sample
  labels:
    name: sample

---
apiVersion: v1
kind: Pod
metadata:
  name: sample
  namespace: sample
  labels:
    name: sample
spec:
  containers:
  - name: sample
    image: hello-world
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: sample
  namespace: sample
spec:
  type: NodePort
  selector:
    app: sample
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sample
  namespace: sample
spec:
  replicas: 1
  selector:
    app: sample
  template:
    metadata:
      name: sample
      labels:
        app: sample
    spec:
      containers:
        - name: sample
          image: hello-world
          ports:
            - containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
spec:
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        image: hello-world
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
