apiVersion: v1
kind: Service
metadata:
  labels:
    name: kickstart-app
  name: kickstart-app
spec:
  ports:
    # The port that this service should serve on.
    - port: 5000
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: nginx
  type: LoadBalancer