apiVersion: v1
kind: ReplicationController
metadata:
  name: kickstart-app
spec:
  replicas: 1
  selector:
    app: kickstart-app
  template:
    metadata:
      name: kickstart-app
      labels:
        app: kickstart-app
    spec:
      containers:
      - name: kickstart-app
        image: nginx
        ports:
        - containerPort: 5000